# Generated by Django 5.2.1 on 2025-05-10 09:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=20, null=True)),
                ('payment_status', models.CharField(choices=[('Initiated', 'Initiated'), ('Completed', 'Completed'), ('Failed', 'Failed')], default='Initiated', max_length=100)),
                ('transaction_id', models.CharField(blank=True, default=0, max_length=255, null=True, unique=True)),
                ('gw_order_id', models.CharField(blank=True, default=0, max_length=255, null=True)),
                ('gw_payment_id', models.CharField(blank=True, default=0, max_length=500, null=True)),
                ('gw_response', models.TextField(blank=True, default='', null=True)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('orders', models.ManyToManyField(related_name='payments', to='orders.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
            },
        ),
    ]
