# Generated by Django 5.2.1 on 2025-05-10 09:34

import accounts.models
import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('is_email_verified', models.BooleanField(default=False)),
                ('is_phone_verified', models.BooleanField(default=False)),
                ('password_expire_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Password Expire Date')),
                ('gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('U', 'Unspecified')], default='U', max_length=1)),
                ('date_of_birth', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date of birth')),
                ('contact_number', models.CharField(blank=True, default=0, max_length=15)),
                ('alternate_contact_number', models.CharField(blank=True, default=0, max_length=15, null=True)),
                ('parent_id', models.IntegerField(blank=True, default=0)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date created')),
                ('date_updated', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date created')),
                ('user_type', models.CharField(blank=True, choices=[('visitor', 'Visitor'), ('buyer', 'Buyer'), ('seller', 'Seller'), ('admin', 'Admin'), ('staff', 'Staff')], default='buyer', null=True)),
                ('otp', models.CharField(blank=True, max_length=6, null=True)),
                ('is_deleted', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='Y')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='customuser_set', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='customuser_set_permissions', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'CustomUser',
                'verbose_name_plural': 'Users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postal_address', models.TextField(blank=True, default='Not specified', null=True)),
                ('address_type', models.CharField(blank=True, choices=[('Home', 'Home'), ('Office', 'Office'), ('Other', 'Other')], default='Home', null=True)),
                ('district', models.CharField(blank=True, default='Not Specified', max_length=200, null=True)),
                ('state', models.CharField(blank=True, default='Not Specified', max_length=200, null=True)),
                ('country', models.CharField(blank=True, default='India', max_length=200, null=True)),
                ('pin', models.IntegerField(blank=True, default=0, null=True, verbose_name='Postal Index Number')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Addresses',
            },
        ),
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='Y')),
                ('buyer_profile_pic', models.ImageField(blank=True, max_length=500, null=True, upload_to=accounts.models.profile_pic_file_path)),
                ('introducer', models.CharField(blank=True, default='Unknown', max_length=200)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date created')),
                ('date_updated', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date created')),
                ('is_active', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='Y')),
                ('description', models.TextField(blank=True, null=True)),
                ('aadhaar_number', models.CharField(blank=True, default='000000000000', max_length=12, null=True, verbose_name='Aadhaar Number')),
                ('pan', models.CharField(blank=True, default='000000000000', max_length=12, null=True, verbose_name='Permanent Account Number')),
                ('organization_name', models.CharField(blank=True, default='individual', max_length=300, null=True)),
                ('age', models.IntegerField(blank=True, default=0)),
                ('language', models.CharField(blank=True, default='English', max_length=100, null=True, verbose_name='Language')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Buyer',
                'verbose_name_plural': 'Buyers',
            },
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='Y')),
                ('introducer', models.CharField(blank=True, default=0, max_length=200)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date created')),
                ('date_updated', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date created')),
                ('is_active', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='Y')),
                ('is_approved', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='Y')),
                ('approval_status', models.CharField(blank=True, default='Pending', max_length=200)),
                ('approved_by', models.CharField(blank=True, default='Unknown', max_length=200)),
                ('approved_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date created')),
                ('store_name', models.CharField(max_length=255)),
                ('store_description', models.TextField()),
                ('store_approved', models.BooleanField(default=False)),
                ('store_address', models.TextField()),
                ('bank_name', models.CharField(max_length=200)),
                ('bank_branch', models.CharField(max_length=200)),
                ('account_no', models.CharField(max_length=100)),
                ('ifsc', models.CharField(max_length=100)),
                ('seller_profile_pic', models.ImageField(blank=True, max_length=500, null=True, upload_to=accounts.models.profile_pic_file_path)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Not Active', 'Not Active')], default='Active', max_length=100)),
                ('description', models.TextField()),
                ('postal_address', models.TextField(blank=True, default='Not specified', null=True)),
                ('branch', models.CharField(max_length=100)),
                ('district', models.CharField(blank=True, default='Not Specified', max_length=200, null=True)),
                ('state', models.CharField(blank=True, default='Not Specified', max_length=200, null=True)),
                ('country', models.CharField(blank=True, default='India', max_length=200, null=True)),
                ('pin', models.IntegerField(blank=True, default=0, null=True, verbose_name='Postal Index Number')),
                ('aadhaar_number', models.CharField(blank=True, default='000000000000', max_length=12, null=True, verbose_name='Aadhaar Number')),
                ('pan', models.CharField(blank=True, default='000000000000', max_length=12, null=True, verbose_name='Permanent Account Number')),
                ('gstn', models.CharField(blank=True, default='0000000000', max_length=100, null=True, verbose_name='GST Number')),
                ('organization_name', models.CharField(blank=True, default='individual', max_length=300, null=True)),
                ('age', models.IntegerField(blank=True, default=0)),
                ('language', models.CharField(blank=True, default='English', max_length=100, null=True, verbose_name='Language')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Seller',
                'verbose_name_plural': 'Sellers',
            },
        ),
        migrations.CreateModel(
            name='UserKYC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(blank=True, max_length=500, null=True, upload_to=accounts.models.user_kyc_image_path)),
                ('aadhaar_image', models.ImageField(blank=True, max_length=500, null=True, upload_to=accounts.models.user_kyc_image_path)),
                ('pan_image', models.ImageField(blank=True, max_length=500, null=True, upload_to=accounts.models.user_kyc_image_path)),
                ('bankstatement_image', models.ImageField(blank=True, max_length=500, null=True, upload_to=accounts.models.user_kyc_image_path)),
                ('affidavit_image', models.ImageField(blank=True, max_length=500, null=True, upload_to=accounts.models.user_kyc_image_path)),
                ('gst_image', models.ImageField(blank=True, max_length=500, null=True, upload_to=accounts.models.user_kyc_image_path)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'UserKYC',
                'verbose_name_plural': 'KYCDocs',
            },
        ),
    ]
