# Generated by Django 5.2.1 on 2025-05-10 09:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('order_status', models.CharField(choices=[('Placed', 'Placed'), ('Completed', 'Completed'), ('Incomplete', 'Incomplete'), ('Canceled', 'Canceled')], default='Pending', max_length=20)),
                ('order_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='Y')),
                ('unit_rate', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('order_amount', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('delivery_charges', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('cgst', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('sgst', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('delivery_date', models.DateTimeField(auto_now_add=True)),
                ('delivery_status', models.CharField(choices=[('Notdelivered', 'Not Delivered'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered'), ('Undelivered', 'Undelivered'), ('Door Closed', 'Door Closed'), ('Dispatched', 'Dispatched'), ('Canceled', 'Canceled')], default='Not Delivered')),
                ('address_type', models.CharField(choices=[('Home', 'Home'), ('Office', 'Office'), ('Other', 'Other')], default='Home')),
                ('delivery_address', models.CharField(blank=True, default='', null=True)),
                ('transaction_id', models.CharField(blank=True, max_length=255, null=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('inventory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.inventory')),
                ('invoice_no', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.invoice')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
    ]
